### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by johnnyasantoss** [jaswdr/docker-image-sybase#1]
I believe that this image is not working :(

```text
 starting container process caused "exec: \"dbsrv16\": executable file not found in $PATH".
```

**Comment by johnnyasantoss** [comment]
Cloning the repo and building worked, but the image in the docker hub still failing.

**Comment by I050689** [comment]
Hi,

What are the parameters for docker run ?
I have the same error message as johnnyasantoss.

Thank you

**Comment by I050689** [comment]
Hi,

I created the container but is not starting. I have the next error message 👍 dbsrv16: error while loading shared libraries: /opt/sqlanywhere16/lib64/libdbserv16_r.so: file too short

Any ideas?

Thank you

**Comment by jaswdr** [comment]
@I050689 did you use direct from the Docker Hub ? with `docker run` command ?

**Comment by I050689** [comment]
Hi Jonathan,

Yes I did.
docker run --name asa16 -d  -v /var/lib/docker/sqlanywhere16/:/opt/sqlanywhere16 jaschweder/Sybase

I have the error :  dbsrv16: error while loading shared libraries: /opt/sqlanywhere16/lib64/libdbserv16_r.so: file too short

I have the sources on /var/lib/docker/sqlanywhere16.

Thank you for your answer. It is very kind of you.
Daniela

**Comment by I050689** [comment]
yes. i took it from docker hub

**Comment by I050689** [comment]
root@dbu16asa16i012:~# docker pull jaschweder/sybase
Using default tag: latest
latest: Pulling from jaschweder/sybase
75c416ea735c: Pull complete
c6ff40b6d658: Pull complete
a7050fc1f338: Pull complete
f0ffb5cf6ba9: Pull complete
be232718519c: Pull complete
afde8cd53bef: Pull complete
Digest: sha256:1b4cfbfd95b12acf69a0cc58a420d1182a1b54329ecbab5cdc78d4a3f8b138f8
Status: Downloaded newer image for jaschweder/sybase:latest
root@dbu16asa16i012:~# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
jaschweder/sybase   latest              529016e775ec        2 days ago          326.1 MB
ubuntu              16.04               dd6f76d9cc90        6 days ago          122 MB
ubuntu              14.04               3aa18c7568fc        6 days ago          188 MB
centos              7                   196e0ce0c9fb        8 weeks ago         196.6 MB
root@dbu16asa16i012:~# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@dbu16asa16i012:~# docker run --name asa16 -d -v /var/lib/docker/sqlanywhere16/:/opt/sqlanywhere16 jaschweder/sybase
416fe96caafdd623141daea41d06953ef9a8d2ba891ed35ff27f3020f596da42
root@dbu16asa16i012:~# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                       PORTS               NAMES
416fe96caafd        jaschweder/sybase   "dbsrv16 /opt/sqlanyw"   4 seconds ago       Exited (127) 3 seconds ago                       asa16
root@dbu16asa16i012:~# docker logs asa16
dbsrv16: error while loading shared libraries: /opt/sqlanywhere16/lib64/libdbserv16_r.so: file too short

**Comment by reywang18** [comment]
can we have this docker run under Windows 10 pro env?

**Comment by alejandrovelez7** [comment]
@jaswdr possible some of the sqlanywhere libs were cut off on github? Did you have to use git lfs for any? 

@I050689 do you still encounter the issue if you pull and then run instead of building from the github repo?

**Comment by ResumeNothing** [comment]
@jaswdr I ran into the same issue and was able to resolve it with #2.

**Comment by jaswdr** [comment]
@ResumeNothing I merged your PR

tested locally, running from Fedora 29 works

I also pushed the image to `jaschweder/sybase` in docker registry, now everyone can have a updated and working image, please run `docker pull jaschweder/sybase` to get the last version.

please @alejandrovelez7 @reywang18 @johnnyasantoss @I050689 take a look if possible

I'm closing this issue for now, if anyone have any new problems, please comment and I'll re-open.
