### ISSUE TITLE
JDBC connection

### ISSUE THREAD

**Issue by dprutean** [jaswdr/docker-image-sybase#4]
Hello,
Thank you for this docker container. 
I tried to connect to it using JDBC driver ( namely using the designer from dbschema.com ) but some reason the login does not work. Do you know how may I debug the connectivity issues ? 
If I do locker logs no records are shown.

**Comment by jaswdr** [comment]
@dprutean can you put here the docker run command you are using? this seems to be a problem with port forward

**Comment by jaswdr** [comment]
@dprutean can you check if you are binding the ports with the `-p` option? also can you try to connect using user `sa` and password `password`.

**Comment by enov** [comment]
I tried to connect using user `dba` and password `sql` and it worked!
