### ISSUE TITLE
wrong creds and files non-exec

### ISSUE THREAD

**Issue by tb3088** [jaswdr/docker-image-sybase#7]
of the 3 sets of creds, only 'dba' works. Could you please update your image so that `guest` and `sa` work as well. Or just remove the wrong ones from the page and from DockerHub documentation.

Also why are all the files in bin64/ missing the execute bit?

**Comment by jaswdr** [comment]
@tb3088 thank you for reaching out. I'll remove the non-dba users since I don't have the files anymore.

About the non-execute bit in `bin64/`, not all files are missing the execute bit, `dbsrv16` has it. But the why is basically because that is how the files are vend, I haven't changed it.
